# Generated by Django 5.0.2 on 2024-02-29 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plant',
            old_name='date',
            new_name='datePlanted',
        ),
        migrations.RenameField(
            model_name='plant',
            old_name='name',
            new_name='plantName',
        ),
    ]
