# Generated by Django 5.0.2 on 2024-03-22 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profileImg',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics'),
        ),
    ]
